name: Lighthouse CI

on:
  push:
    branches: [ main ]

jobs:
  lighthouseci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - run: npm ci

      - run: npm run build

      - name: Run LHCI
        run: |
          npx @lhci/cli autorun \
            --config=./lighthouserc.json \
            --upload.target=temporary-public-storage \
            --upload.githubToken=${{ secrets.LHCI_GITHUB_APP_TOKEN }}
